import type { AnalysisResult } from "./types";
import { prettyComplexity as pc } from "./format";

/**
 * Render an analysis result as a shareable Markdown report. Pure/deterministic
 * so it's testable without the API. Used by the (flag-gated) Export action.
 */
export function analysisToMarkdown(opts: {
  fileName: string;
  language: string;
  result: AnalysisResult;
}): string {
  const { fileName, language, result } = opts;
  const out: string[] = [];

  out.push(`# Profiler report — ${fileName}`, "");
  out.push(`- **Language:** ${language}`);
  out.push(`- **Overall:** ${pc(result.overallComplexity)}`);
  if (result.complexityReasoning) out.push(`- ${pc(result.complexityReasoning)}`);
  out.push("");

  out.push(`## Hotspots (${result.hotspots.length})`);
  if (result.hotspots.length === 0) out.push("", "_None flagged._");
  result.hotspots.forEach((h, i) => {
    const range = `L${h.startLine}${h.endLine !== h.startLine ? `–${h.endLine}` : ""}`;
    const conf = typeof h.confidence === "number" ? ` · ${h.confidence}% confidence` : "";
    out.push("", `### ${i + 1}. ${pc(h.issue)}  \`${range}\` · ${h.severity}${conf}`);
    out.push(pc(h.explanation), "", `**Fix:** ${pc(h.suggestion)}`);
    if (h.algorithm) out.push(`**Better fit:** ${pc(h.algorithm)}`);

    const fixes =
      h.fixes && h.fixes.length > 0
        ? h.fixes
        : h.suggestedCode
        ? [{ id: "", title: "Suggested rewrite", code: h.suggestedCode, source: "ai" as const }]
        : [];
    if (fixes.length > 1) out.push("", `_${fixes.length} fix options:_`);
    fixes.forEach((f) => {
      const src = f.source === "rule" ? " (rule)" : "";
      const rec = f.recommended ? " ✓" : "";
      const tags = f.tradeoffs && f.tradeoffs.length > 0 ? ` — _${f.tradeoffs.join(" · ")}_` : "";
      out.push("", `**${f.title}**${rec}${src}${tags}`, "```" + language, f.code, "```");
    });
  });

  if (result.flameGraph && result.flameGraph.length > 0) {
    out.push("", "## Estimated cost breakdown");
    [...result.flameGraph]
      .sort((a, b) => b.weight - a.weight)
      .forEach((n) => out.push(`- ${n.label} — ${pc(n.complexity)} (weight ${n.weight})`));
  }

  out.push("", "_Generated by Profiler · estimates, not measured runtime._");
  return out.join("\n");
}
