import type { AnalysisResult } from "./types";

/**
 * Render an analysis result as a shareable Markdown report. Pure/deterministic
 * so it's testable without the API. Used by the (flag-gated) Export action.
 */
export function analysisToMarkdown(opts: {
  fileName: string;
  language: string;
  result: AnalysisResult;
}): string {
  const { fileName, language, result } = opts;
  const out: string[] = [];

  out.push(`# Profiler report — ${fileName}`, "");
  out.push(`- **Language:** ${language}`);
  out.push(`- **Overall:** ${result.overallComplexity}`);
  if (result.complexityReasoning) out.push(`- ${result.complexityReasoning}`);
  out.push("");

  out.push(`## Hotspots (${result.hotspots.length})`);
  if (result.hotspots.length === 0) out.push("", "_None flagged._");
  result.hotspots.forEach((h, i) => {
    const range = `L${h.startLine}${h.endLine !== h.startLine ? `–${h.endLine}` : ""}`;
    out.push("", `### ${i + 1}. ${h.issue}  \`${range}\` · ${h.severity}`);
    out.push(h.explanation, "", `**Fix:** ${h.suggestion}`);
    if (h.algorithm) out.push(`**Better fit:** ${h.algorithm}`);
    if (h.suggestedCode) out.push("", "```" + language, h.suggestedCode, "```");
  });

  if (result.flameGraph && result.flameGraph.length > 0) {
    out.push("", "## Estimated cost breakdown");
    [...result.flameGraph]
      .sort((a, b) => b.weight - a.weight)
      .forEach((n) => out.push(`- ${n.label} — ${n.complexity} (weight ${n.weight})`));
  }

  out.push("", "_Generated by Profiler · estimates, not measured runtime._");
  return out.join("\n");
}
